### ISSUE TITLE
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

### ISSUE THREAD

**Issue by subodhkalika** [singlestore-labs/start-with-singlestore-python#1]
docker-compose up is working. Was able to connect to localhost and test the database out.

Facing this issue when running
python main.py
```

Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main()
  File "main.py", line 15, in main
    conn = database.connect(host=HOST, port=PORT, user=USER, password=PASSWORD, database=DATABASE)
  File "/home/user/environments/my_env/lib/python3.6/site-packages/memsql/common/database.py", line 19, in connect
    return Connection(*args, **kwargs)
  File "/home/user/environments/my_env/lib/python3.6/site-packages/memsql/common/database.py", line 62, in __init__
    self.reconnect()
  File "/home/user/environments/my_env/lib/python3.6/site-packages/memsql/common/database.py", line 93, in reconnect
    conn = _mysql.connect(**self._db_args)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

```

**Comment by subodhkalika** [comment]
Found solution in [this link](https://www.singlestore.com/forum/t/cant-connect-to-memsql-via-python/2815).

I was providing host = 'localhost' on main.py
When replaced by 127.0.0.1. It worked. 

conn = database.connect(host="127.0.0.1", port=3306, user="root", password="password_here", database="acme)
